baseurl = "https://avnishsachar.github.io"
title = "AVNISH SACHAR"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
copyright = false
relativeURLs = true

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "avnishsachar"
#googleAnalytics = ""
publishDir = "avnishsachar.github.io"

[params]
    author = "Hi, I'm Avnish! Currently a Robotics Grad student @WPI"
    info = "I make robots think, plan, and move using software."
    description = "Avnish Sachar's personal website"
    keywords = "blog,developer,personal,robotics,wpi,san fransisco,worcester,boston,software,sde,engineer"
    avatarurl = "img/avatar.jpg"

    favicon_32 = "img/rob_favicon.png"
    favicon_16 = "img/rob_favicon.png"

    footercontent = ""
    dateformat = "January 2, 2006"

    hideFooter = true
    hideCredits = false
    hideCopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

    maxSeeAlsoItems = 5

    enableTwemoji = true

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"
    
# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
    domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/avnishsachar/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/avnishsachar/"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope"
    weight = 6
    url = "mailto:asachar@wpi.edu"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/avnishsachar/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 4
    url = "https://twitter.com/sacharavnish/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 5
    url = "https://instagram.com/avnishsachar/"
[[params.social]]
    name = "Spotify"
    icon = "fab fa-spotify"
    weight = 7
    url = "https://open.spotify.com/user/avnishsachar?si=vjXVS_-xSxeoi6AneZSHZg"
    

# Menu links
    [[menu.main]]
    name = "about"
    weight = 1
    url = "about/"
#[[menu.main]]
#    name = "research"
#    weight = 3
#    url  = "/research/"
    [[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 2
    url  = "projects/"
#[[menu.main]]
#    name = "work"
#    weight = 4
#    url  = "/work/"
#[[menu.main]]
#    name = "blog"
#    weight = 5
#    url  = "/blog/"
    [[menu.main]]
    name = "resume"
    weight = 3
    url  = "https://drive.google.com/file/d/1z2dhsJ01SELIqk516QcrcP9gGVwx3R3N/view?usp=sharing"